name: workflow_01
on:
  workflow_dispatch:
     inputs:
      workflow_02:
        description: Workflow 2 which will be triggered
        required: true
        default: workflow_02

      workflow2_PGM02C_UT:
        description: Topaz total test
        required: true
        default: saikirangan

      workflow2_repo_github:
        description: PGM02C_UT
        required: true
        default: 'PGM02C_UT' 

jobs:
  build:
    runs-on: Self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/:userName/:repoName/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PGM02C_UT }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3
